-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "public"."_ponder_checkpoint" (
    "chain_name" TEXT NOT NULL,
    "chain_id" BIGINT NOT NULL,
    "safe_checkpoint" VARCHAR(75) NOT NULL,
    "latest_checkpoint" VARCHAR(75) NOT NULL,
    "finalized_checkpoint" VARCHAR(75) NOT NULL,

    CONSTRAINT "_ponder_checkpoint_pkey" PRIMARY KEY ("chain_name")
);

-- CreateTable
CREATE TABLE "public"."_ponder_meta" (
    "key" TEXT NOT NULL,
    "value" JSONB NOT NULL,

    CONSTRAINT "_ponder_meta_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "public"."_reorg__ownership" (
    "id" TEXT NOT NULL,
    "contract_address" TEXT NOT NULL,
    "user" TEXT NOT NULL,
    "balance" DECIMAL(78,0) NOT NULL,
    "last_updated" DECIMAL(78,0) NOT NULL,
    "last_updated_block" DECIMAL(78,0) NOT NULL,
    "product_id" TEXT NOT NULL,
    "operation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "operation" INTEGER NOT NULL,
    "checkpoint" VARCHAR(75) NOT NULL,

    CONSTRAINT "_reorg__ownership_pkey" PRIMARY KEY ("operation_id")
);

-- CreateTable
CREATE TABLE "public"."_reorg__product_onchain" (
    "id" TEXT NOT NULL,
    "sequence_id" DECIMAL(78,0) NOT NULL,
    "contract_address" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "max_supply" DECIMAL(78,0) NOT NULL,
    "total_supply" DECIMAL(78,0) NOT NULL,
    "factory_address" TEXT NOT NULL,
    "created_at" DECIMAL(78,0) NOT NULL,
    "created_at_block" DECIMAL(78,0) NOT NULL,
    "created_at_transaction" TEXT NOT NULL,
    "holder_count" DECIMAL(78,0) NOT NULL,
    "operation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "operation" INTEGER NOT NULL,
    "checkpoint" VARCHAR(75) NOT NULL,

    CONSTRAINT "_reorg__product_onchain_pkey" PRIMARY KEY ("operation_id")
);

-- CreateTable
CREATE TABLE "public"."_reorg__transaction_logs" (
    "id" TEXT NOT NULL,
    "contract_address" TEXT NOT NULL,
    "user" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "token_amount" DECIMAL(78,0) NOT NULL,
    "usdt_amount" DECIMAL(78,0) NOT NULL,
    "timestamp" DECIMAL(78,0) NOT NULL,
    "block_number" DECIMAL(78,0) NOT NULL,
    "transaction_hash" TEXT NOT NULL,
    "log_index" DECIMAL(78,0) NOT NULL,
    "operation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "operation" INTEGER NOT NULL,
    "checkpoint" VARCHAR(75) NOT NULL,

    CONSTRAINT "_reorg__transaction_logs_pkey" PRIMARY KEY ("operation_id")
);

-- CreateTable
CREATE TABLE "public"."ownership" (
    "id" TEXT NOT NULL,
    "contract_address" TEXT NOT NULL,
    "user" TEXT NOT NULL,
    "balance" DECIMAL(78,0) NOT NULL,
    "last_updated" DECIMAL(78,0) NOT NULL,
    "last_updated_block" DECIMAL(78,0) NOT NULL,
    "product_id" TEXT NOT NULL,

    CONSTRAINT "ownership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."product_onchain" (
    "id" TEXT NOT NULL,
    "sequence_id" DECIMAL(78,0) NOT NULL,
    "contract_address" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "max_supply" DECIMAL(78,0) NOT NULL,
    "total_supply" DECIMAL(78,0) NOT NULL,
    "factory_address" TEXT NOT NULL,
    "created_at" DECIMAL(78,0) NOT NULL,
    "created_at_block" DECIMAL(78,0) NOT NULL,
    "created_at_transaction" TEXT NOT NULL,
    "holder_count" DECIMAL(78,0) NOT NULL,

    CONSTRAINT "product_onchain_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."transaction_logs" (
    "id" TEXT NOT NULL,
    "contract_address" TEXT NOT NULL,
    "user" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "token_amount" DECIMAL(78,0) NOT NULL,
    "usdt_amount" DECIMAL(78,0) NOT NULL,
    "timestamp" DECIMAL(78,0) NOT NULL,
    "block_number" DECIMAL(78,0) NOT NULL,
    "transaction_hash" TEXT NOT NULL,
    "log_index" DECIMAL(78,0) NOT NULL,

    CONSTRAINT "transaction_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ownership_checkpoint_index" ON "public"."_reorg__ownership"("checkpoint" ASC);

-- CreateIndex
CREATE INDEX "product_onchain_checkpoint_index" ON "public"."_reorg__product_onchain"("checkpoint" ASC);

-- CreateIndex
CREATE INDEX "transaction_logs_checkpoint_index" ON "public"."_reorg__transaction_logs"("checkpoint" ASC);

